apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndbskjhsyie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndbskjhsyie
  template:
    metadata:
      labels:
        app: ndbskjhsyie
    spec:
      containers:
      - image: okteto.dev/ndbskjhsyie:latest
        name: ndbskjhsyie
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a4e3fe90-e9c2-46b1-9b61-a860c5d4ddd1"
        - name: Vless_Path
          value: "/a4e3fe90-e9c2-46b1-9b61-a860c5d4ddd1-vless"
        - name: Vmess_UUID
          value: "a4e3fe90-e9c2-46b1-9b61-a860c5d4ddd1"
        - name: Vmess_Path
          value: "/a4e3fe90-e9c2-46b1-9b61-a860c5d4ddd1-vmess"
        - name: Share_Path
          value: "/v2link"
